#!/bin/bash 

subj=$1
WORKDIR=$2

#Full diffusion pipeline, from pre-processing to connectome construction

#Basic preprocessing

basicpreproc $subj $WORKDIR

#Fiber construction

basicfibertrack $subj $WORKDIR 5M

#Connectome construction

basiccntmecon $subj $WORKDIR /home/beegfs/perry/working/COBRA/C_Standards/Schaefer200_plus_HO.nii 5M Schae200
