#!/bin/bash
#Template file which sets up requirements for slurm

#SBATCH -n 1 # 1 per CPU
#SBATCH -c 8 # number of cpus per task
#SBATCH --nice=20
#SBATCH -p blade-a

####
#Load all required software - sure this is not the case for MPI
module load mrtrix3/3.0_RC3
module load freesurfer/6.0.0
module load ANTs/20160509
module load fsl/5.0.9_eddy

export OMP_NUM_THREADS=8

####
####
#Find all the relevant scripting files
pipedir=&&&&
PATH=$PATH$( find $pipedir/ -not -path '*/\.*'  -type d -printf ":%p" )

#Extract ID of subject and their corresponding folder holding raw image files

subj=@@@@
subjDIRECTORY=????

cd $subjDIRECTORY

%%%% #"%%%%" will match to the string  that corresponds to your personalised batch script, or preferred pipeline
 
