#!/bin/bash
#file : prepareglasserparc
#usage: prepareglasserparc <WORKDIR> <OUTDIR>

#Template file which sets up PBS requirements for all job

WORKDIR=$1

export OMP_NUM_THREADS=$ncpus

export SUBJECTS_DIR=${WORKDIR}/FS
OUTDIR=$SUBJECTS_DIR/glasser

cd $SUBJECTS_DIR

if [ -z "$subjlist" ]
then

find ${WORKDIR}/Raw/* -maxdepth 0 -type d | awk -F "/" '{print $NF}' - > subjlist.txt
subjlist=${SUBJECTS_DIR}/subjlist.txt

fi

#printf $(basename $subjfilelist) > subjlist.txt

if [ ! -d fsaverage ]; then

rsync -vaz ${FREESURFER_HOME}/subjects/fsaverage .

fi

if [ ! -f create_subj_volume_parcellation.sh ]; then

rsync ~/diffusion-pipeline/miscscripts/create_subj_volume_parcellation.sh .

fi

if [ ! -f lh.HCPMMP1.annot ]; then

rsync ~/diffusion-pipeline/data/lh.HCPMMP1.annot .
rsync ~/diffusion-pipeline/data/rh.HCPMMP1.annot .

fi

bash create_subj_volume_parcellation.sh -L $subjlist -a HCPMMP1 -d ${OUTDIR} -m "YES"
