#!/bin/bash
subj=$1
WORKDIR=$2

tckbasename=$3

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

mkdir -p ${WORKDIR}/QC
mkdir -p ${WORKDIR}/QC/Masks
mkdir -p ${WORKDIR}/QC/FA
mkdir -p ${WORKDIR}/QC/meanDWI
mkdir -p ${WORKDIR}/QC/gmwmi
mkdir -p ${WORKDIR}/QC/tdi
mkdir -p ${WORKDIR}/QC/parc
mkdir -p ${WORKDIR}/QC/coreg

nshells=$(mrinfo meanshell.mif -size)
lastdwidim=$(echo $nshells | awk -F " " '{print $NF}')

#fa

slicer fa.nii -a fa_sliced.ppm
convert fa_sliced.ppm ${WORKDIR}/QC/FA/${subj}_fa.png


#main diffusion-weighted volume

mrconvert meanshell.mif meandwishell.nii -coord 3 $(( $lastdwidim-1 )) -nthreads 1
slicer meandwishell.nii -a meandwi_sliced.ppm
convert meandwi_sliced.ppm ${WORKDIR}/QC/meanDWI/${subj}_meandwi.png


#masks

overlay 1 1 meandwishell.nii -A biasmeanb0bet.nii.gz 1 10 mask_overlay.nii.gz
cp slicesdir/mask_overlay.png ${WORKDIR}/QC/Masks/${subj}_maskoverlay.png
rm -rf slicesdir


#gmwmi

overlay 1 0 brainFSnat.nii -A 5TTgmwmi.nii 0.25 1 gmwmi_overlay.nii.gz
slicer gmwmi_overlay.nii.gz -a gmwmioverlay_sliced.ppm
convert gmwmioverlay_sliced.ppm ${WORKDIR}/QC/gmwmi/${subj}_gmwmioverlay.png


#alignment between anatomical and diffusion images

overlay 1 0 rFSrg.nii -A fa.nii 0.25 1.5 FA_overlay_onT1.nii.gz
slicer FA_overlay_onT1.nii.gz  -a FAoverlayonT1_sliced.ppm
convert FAoverlayonT1_sliced.ppm ${WORKDIR}/QC/coreg/${subj}_FAoverlayonT1.png 


#parcellation overlap 

overlay 1 1 fa.nii -A rparc_fixsubcort.nii 1 `fslstats rparc_fixsubcort.nii -R | awk -F " " '{print $2}'` parc_overlay.nii.gz
slicer parc_overlay.nii.gz  -a parcoverlay_sliced.ppm
convert parcoverlay_sliced.ppm ${WORKDIR}/QC/parc/${subj}_parcoverlay.png 
rm parc_overlay.nii.gz


#track densities

slicer  ${tckbasename}.nii -a tdi_sliced.ppm
convert tdi_sliced.ppm ${WORKDIR}/QC/tdi/${subj}_tdi.png


rm *.ppm
