#!/bin/bash
# file: processFSall

subj=$1
WORKDIR=$2

SUBJECTS_DIR=${WORKDIR}/FS
mkdir -p ${SUBJECTS_DIR}

recon-all -all -i anat/sub-${subj}_T1w.nii.gz -subjid $subj -sd $SUBJECTS_DIR -no-isrunning -mprage
